export const MEDHA_TOPICS = {
    COMMONVARIABLES:'BE/FE/MEDHA/COMMONVARIABLES',
    HOMESCREEN:'BE/FE/MEDHA/HOMESCREEN',
    LOCOSTATUS:'BE/FE/MEDHA/LOCOSTATUS',
    LIFETIMEDATA:'BE/FE/MEDHA/LIFETIMEDATA',
    MONTHLYDATA:'BE/FE/MEDHA/MONTHLYDATA',
    TRACTIONMOTOR:'BE/FE/MEDHA/TRACTIONMOTOR',
    TRIPDATA:'BE/FE/MEDHA/TRIPDATA',
    ACTIVEFAULT:'BE/FE/FAULT/ACTIVEFAULTS',
    INACTIVEFAULTS:'BE/FE/FAULT/INACTIVEFAULTS',
    ENTIREFAULTS:'BE/FE/FAULT/ENTIREFAULTS',
    INCHINGMODE:'BE/FE/MEDHA/INCHINGMODE',
    PUBLISHINCHINGMODE:'FE/BE/MEDHA/INCHINGMODE',
    BROWSELOCOS:'BE/FE/MEDHA/BROWSEMODE',
    BROWSELOCOSSS:'BE/FE/MEDHA/BROWSEMODE/SS'
}
   
