import { create } from "zustand";
export const useReplicaStore = create((set) => ({
  // cabReplicaData: {
  //   location: 0,
  //   energize_state: 0,
  //   flasher_light: 0,
  //   uba_battery: 0,
  //   u_catenary: 0,
  //   bogie_1_tebe_meter: 0,
  //   bogie_2_tebe_meter: 0,
  //   zban: 0,
  //   lsdj: 0,
  //   lsho: 0,
  //   lsp: 0,
  //   lsaf: 0,
  //   lsvw: 0,
  //   lsce: 0,
  //   display_screen: 0,
  //   bl_key_previous: 0,
  //   bl_key_current: 0,
  //   switch_off_state: 0,
  //   cooling_state: 0,
  //   emergency_push_button: 0,
  //   zpt: 0,
  //   bldj: 0,
  //   blcp: 0,
  //   blho: 0,
  //   changeCab: 0,
  //   changeMultipleCab: 0,
  //   ztel: 0,
  //   bpcs_button: 0,
  //   bpcs_light: 0,
  //   bppb_light: 0,
  //   bppb_button: 0,
  //   bpvr_button: 0,
  //   bpvr_light: 0,
  //   mce: 0,
  //   bcp_bogie_1: 0,
  //   bcp_bogie_2: 0,
  //   feed_pipe_pressure: 0,
  //   main_reservoir_pressure: 0,
  //   air_flow_meter: 0,
  //   brake_pipe_pressure: 0,
  //   lsfi: 0,
  //   bpfl: 0,
  //   bpfi: 0,
  //   zlc: 0,
  //   zli: 0,
  //   zldd: 0,
  //   bz_v_o_f: 0,
  //   bpfa_light: 0,
  //   bpfa_button: 0,
  //   speed: 0,
  //   zlda: 0,
  //   bpvg: 0,
  //   pclh: 0,
  //   zlh: 0,
  //   reverser: 0,
  //   throttle: 0,
  //   memotel: 0,
  //   sa_9: 0,
  //   a_9: 1,
  //   parkingBrake: 0,
  //   sanding: 0,
  //   pvef: 0,
  //   vigilance: 0,
  //   vcd_timer: 0,
  //   horn: 0,
  //   loco_operation_mode: "s",
  //   zlfw: 0,
  //   zlfr: 0,
  //   zprd: 0,
  //   message: "",
  //   flg: 0,
  //   mce_stage: 0,
  //   is_emergency_applied: 0,
  //   vigilance_timer: 0,
  //   bogie_isolation: 0,
  //   battery_fault: 0,
  //   fault: 0,
  //   wagons: 0,
  // },
  cabReplicaData: {},
  updateReplicaData: (data) =>
    set((state) => {
      // let tempData = state.cabReplicaData;
      // Object.keys(data)?.forEach((key) => {
      //   tempData[key] = data[key];
      // });
      // return {
      //   cabReplicaData: tempData,
      // };
      return {
        cabReplicaData: data,
      };
    }),
}));
